apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: colors
    version: v1
resources:
- global-lb.yaml
- pdb.yaml
- https://github.com/vrutkovs/kcd-cz-demo//pipelines/prod?ref=main
