---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: colors
  name: colors
spec:
  selector:
    matchLabels:
      app: colors
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: colors
    spec:
      containers:
      - image: ghcr.io/vrutkovs/color-demo:latest
        name: colors
        env:
        - name: COLOR
          value: "blue"
        - name: TITLE
          value: "dev server"
        resources: {}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
